/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_SHAREDIR "/usr/local/share/qemu"
#define HOST_X86_64 1
#define HOST_LONG_BITS 64
#define CONFIG_POSIX 1
#define CONFIG_LINUX 1
#define CONFIG_SLIRP 1
#define CONFIG_AC97 1
#define CONFIG_ES1370 1
#define CONFIG_SB16 1
#define CONFIG_AUDIO_DRIVERS \
    &oss_audio_driver,\

#define CONFIG_OSS 1
#define CONFIG_BDRV_WHITELIST \
    NULL
#define CONFIG_VNC_SASL 1
#define CONFIG_FNMATCH 1
#define CONFIG_UUID 1
#define QEMU_VERSION "0.12.2"
#define QEMU_PKGVERSION ""
#define CONFIG_CURSES 1
#define CONFIG_BYTESWAP_H 1
#define CONFIG_IOVEC 1
#define CONFIG_FDATASYNC 1
#define CONFIG_UNAME_RELEASE ""
#define CONFIG_ZERO_MALLOC 1
